import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import { useDocumentMeta } from "../lib/useDocumentMeta";
import { PARENT_STORIES } from "../data/company";

export default function HallOfFamePage() {
  useDocumentMeta("Hall of Fame – Vinh danh học viên | VMG", "Thành tích IELTS, lễ trao chứng chỉ Cambridge và những chia sẻ thật của phụ huynh trong hành trình học tập tại VMG.");
  return <div className="min-h-screen flex flex-col"><Header /><main className="flex-1">
    <section className="bg-[#2b1116] text-white py-16 md:py-24"><div className="container-vmg"><p className="text-gold-soft text-xs font-bold uppercase tracking-widest">Vinh danh học viên VMG</p><h1 className="mt-3 font-display text-4xl md:text-6xl font-extrabold">Hall of Fame</h1><p className="mt-5 max-w-2xl text-white/75 leading-7">Mỗi cột mốc là dấu ấn của sự nỗ lực. Cùng nhìn lại những thành quả và câu chuyện trưởng thành của học viên VMG.</p></div></section>
    <section className="container-vmg py-14 md:py-20"><h2 className="text-2xl md:text-3xl font-display font-extrabold">Những cột mốc IELTS</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Array.from({length: 16}, (_, index) => <a key={index} href={`/hall-of-fame/ielts-${String(index + 1).padStart(2,"0")}.webp`} target="_blank" rel="noreferrer" aria-label={`Mở ảnh vinh danh IELTS ${index + 1}`} className="overflow-hidden rounded-2xl border border-neutral-200"><img src={`/hall-of-fame/ielts-${String(index + 1).padStart(2,"0")}.webp`} alt={`Bảng vinh danh học viên IELTS VMG ${index + 1}`} className="w-full h-auto" loading="lazy" /></a>)}</div></section>
    <section className="bg-cream py-14"><div className="container-vmg grid gap-8 md:grid-cols-2">
      <article className="rounded-3xl bg-white p-7"><p className="text-xs font-bold uppercase tracking-widest text-brand">Câu chuyện học viên</p><h2 className="mt-3 font-display text-2xl font-bold">Thanh Như · Hành trình chinh phục IELTS 7.0</h2><p className="mt-4 text-sm leading-7 text-neutral-600">Câu chuyện trưởng thành và chinh phục IELTS 7.0 của Thanh Như được VMG chia sẻ trong thư viện trải nghiệm học viên.</p><a href="https://www.youtube.com/watch?v=AvdrGKyxBzM" target="_blank" rel="noreferrer" className="mt-6 inline-block text-sm font-bold text-brand">Xem video câu chuyện ↗</a></article>
      <a href="/tin-tuc/vinh-danh-cambridge-2026" className="overflow-hidden rounded-3xl bg-white"><img src="/legacy/cambridge-2026.jpg" alt="Lễ trao chứng chỉ Cambridge cho học viên VMG Long Thành và Nhơn Trạch" className="w-full aspect-[16/9] object-cover" loading="lazy" /><h2 className="p-7 font-display text-xl font-bold">Vinh danh học viên Cambridge 2026 →</h2></a>
    </div></section>
    <section className="container-vmg py-14 md:py-20"><h2 className="text-2xl md:text-3xl font-display font-extrabold">Phụ huynh chia sẻ</h2><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{PARENT_STORIES.map((story) => <figure key={story.name} className="rounded-3xl border border-neutral-200 p-7"><blockquote cite="https://vmgenglish.edu.vn/trai-nghiem-hoc-vien.html" className="text-sm leading-7 text-neutral-700">“{story.quote}”</blockquote><figcaption className="mt-6"><p className="font-bold">{story.name}</p><p className="mt-1 text-xs text-neutral-500">{story.location}</p></figcaption></figure>)}</div><a className="mt-6 inline-block text-xs text-neutral-500 underline" href="https://vmgenglish.edu.vn/trai-nghiem-hoc-vien.html" target="_blank" rel="noreferrer">Chia sẻ đã được đăng trên trang Trải nghiệm học viên VMG</a></section>
  </main><Footer /></div>;
}
